### ISSUE TITLE
data release

### ISSUE THREAD

**Issue by tangerzhang** [Arkarachai/falcon_unzip_assessment#1]
Hi, 
Is is possible to release the phased human assembly with fasta format?
Thanks!

**Comment by Arkarachai** [comment]
Yes, I can. We have primary and haplotype contig in fasta format. Do you have DNAnexus account? If not, I can give you the downloadable URL.

**Comment by tangerzhang** [comment]
Hi, my account is zhangxt and email is zhangxt@fafu.edu.cn
Thanks!

**Comment by Arkarachai** [comment]
Sounds good. I just grant you the view access. Here are the file ids
project-F7f1y000YVjY3Jpz8P3QQ6G6:file-F5k8bFQ02zFg3Gbx71P04bFP
project-F7f1y000YVjY3Jpz8P3QQ6G6:file-F5k838j02zFpFK07J2j3x0YJ
Feel free to distribute this data as long as people cite our current preprint and Genome in a Bottle publication who provide initial raw data. 
Also, let me know once you copy data to your project or download it.

**Comment by tangerzhang** [comment]
Thanks, Arkarachai!
I am downloading the data. Just one simple question:  this file "cns_p_ctg.fasta.gz" the phased human genome assembly generated from falcon-unzip program, right?
I just want to make sure that I am downloading the right file.
BTW, I am sure I will cite the publication. Thanks again!

**Comment by Arkarachai** [comment]
Hi,
The cns_p_ctg.fasta.gz is the primary contig and cns_h_ctg.fasta.gz is the haplotype contig from Falcon-unzip. It's phased as pseudohaploid. Basically, each record in cns_h_ctg.fasta.gz is a phasing block of either father mother, while their corresponding section on primary contig would represent the contribution from the other parent. 
Recently, there is an alternative way to represent phased genome as two separated set of contigs. These can be generated by Falcon-Phase (next step from Falcon-Unzip) or trio-binning. I would recommend you to visit their preprint as well. The current release data are on cow though, now human. I expect the phased human data from these technologies should be available soon.

**Comment by Arkarachai** [comment]
Have you had a chance to download the files? If so, I would close this ticket.

**Comment by tangerzhang** [comment]
Yes, I've downloaded these data. Let me close this issue!
Thanks!
